version: 0.2

# CodeBuild BuildSpec for AWS Inspector Vulnerability Scan Validation
# Stage 2: Scan - Wait for Inspector scan and validate results
# Trigger: After Build stage completes and image is pushed to ECR
# Next: Deploy stage (if scan passes validation)

env:
  variables:
    AWS_DEFAULT_REGION: "ap-southeast-1"
    ENVIRONMENT: "sit"  # Override in CodePipeline: sit/uat/prod
    ECR_REPOSITORY_NAME: "hlf-lab-ecr-sit-test-app"
    # AWS Inspector Scan Configuration (environment-specific)
    # SIT: Warn only, no notifications
    # UAT: Warn only, enable notifications  
    # PROD: Block on CRITICAL, enable notifications, allow emergency override
    SCAN_ON_PUSH_ENABLED: "true"
    BLOCK_ON_CRITICAL: "false"  # Set via CodePipeline: false(SIT/UAT), true(PROD)
    ENABLE_NOTIFICATION: "false"  # Set via CodePipeline: false(SIT), true(UAT/PROD)
    SNS_TOPIC_ARN: ""  # Set from CloudFormation parameter
    ALLOW_OVERRIDE: "false"  # Set via CodePipeline: false(SIT/UAT), true(PROD only)
    # Severity thresholds for deployment blocking
    MAX_CRITICAL_FINDINGS: "0"  # Block if CRITICAL > 0 (when BLOCK_ON_CRITICAL=true)
    MAX_HIGH_FINDINGS: "999"  # Currently not blocking on HIGH
phases:
  pre_build:
    commands:
      - echo "=========================================="
      - echo "Stage 2: AWS Inspector Vulnerability Scan Validation"
      - echo "=========================================="
      - echo "Environment=$ENVIRONMENT"
      - echo "ECR Repository=$ECR_REPOSITORY_NAME"
      
      # Get AWS Account ID
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export ECR_REPOSITORY_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}"
      
      # Get IMAGE_TAG from previous build stage artifact or CodeBuild variable
      - |
        if [ -f build-output.json ]; then
          export IMAGE_TAG=$(cat build-output.json | jq -r '.imageTag')
          echo "Image Tag from build artifact: $IMAGE_TAG"
        else
          export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
          echo "Image Tag from CodeBuild: $IMAGE_TAG"
        fi
      
      - echo "Image Tag=$IMAGE_TAG"
      - echo "ECR Repository URI=$ECR_REPOSITORY_URI"
      - echo ""
      - echo "Policy Configuration:"
      - echo "  Block on Critical: $BLOCK_ON_CRITICAL"
      - echo "  Enable Notification: $ENABLE_NOTIFICATION"
      - echo "  Allow Override: $ALLOW_OVERRIDE"
      - echo "=========================================="
      
  build:
    commands:
      - echo "Waiting for AWS Inspector vulnerability scan to complete..."
      - echo "Note: ECR with AWS Inspector automatically scans images on push"
      - echo "Inspector scans for OS and programming language package vulnerabilities"
      
      # Wait for scan to complete (max 10 minutes for Inspector)
      - |
        MAX_WAIT=600  # 10 minutes (Inspector scans can take longer)
        WAIT_INTERVAL=15
        ELAPSED=0
        
        while [ $ELAPSED -lt $MAX_WAIT ]; do
          SCAN_STATUS=$(aws ecr describe-image-scan-findings \
            --repository-name "${ECR_REPOSITORY_NAME}" \
            --image-id imageTag="${IMAGE_TAG}" \
            --region "${AWS_DEFAULT_REGION}" \
            --query 'imageScanStatus.status' \
            --output text 2>/dev/null || echo "PENDING")
          
          echo "Scan status: $SCAN_STATUS (elapsed: ${ELAPSED}s)"
          
          if [ "$SCAN_STATUS" = "COMPLETE" ]; then
            echo "AWS Inspector scan completed successfully"
            break
          elif [ "$SCAN_STATUS" = "FAILED" ]; then
            echo "ERROR: AWS Inspector image scan failed!"
            if [ "$BLOCK_ON_CRITICAL" = "true" ]; then
              exit 1
            else
              echo "WARNING: Continuing despite scan failure (non-blocking mode)"
              exit 0
            fi
          fi
          
          sleep $WAIT_INTERVAL
          ELAPSED=$((ELAPSED + WAIT_INTERVAL))
        done
        
        if [ $ELAPSED -ge $MAX_WAIT ]; then
          echo "WARNING: Scan did not complete within $MAX_WAIT seconds"
          if [ "$BLOCK_ON_CRITICAL" = "true" ]; then
            echo "ERROR: Blocking deployment due to scan timeout in blocking mode"
            exit 1
          else
            echo "WARNING: Continuing despite scan timeout (non-blocking mode)"
            exit 0
          fi
        fi
      
      # Get AWS Inspector scan findings
      - echo "Retrieving AWS Inspector scan findings..."
      - |
        SCAN_FINDINGS=$(aws ecr describe-image-scan-findings \
          --repository-name "${ECR_REPOSITORY_NAME}" \
          --image-id imageTag="${IMAGE_TAG}" \
          --region "${AWS_DEFAULT_REGION}" 2>&1)
        
        if [ $? -ne 0 ]; then
          echo "WARNING: Could not retrieve AWS Inspector scan findings"
          echo "$SCAN_FINDINGS"
          if [ "$BLOCK_ON_CRITICAL" = "true" ]; then
            echo "ERROR: Blocking deployment due to scan retrieval failure"
            exit 1
          else
            echo "WARNING: Continuing despite scan retrieval failure (non-blocking mode)"
            exit 0
          fi
        fi
        
        echo "Successfully retrieved scan findings from AWS Inspector"git a
        
        # Parse findings count
        CRITICAL_COUNT=$(echo "$SCAN_FINDINGS" | jq -r '.imageScanFindings.findingSeverityCounts.CRITICAL // 0')
        HIGH_COUNT=$(echo "$SCAN_FINDINGS" | jq -r '.imageScanFindings.findingSeverityCounts.HIGH // 0')
        MEDIUM_COUNT=$(echo "$SCAN_FINDINGS" | jq -r '.imageScanFindings.findingSeverityCounts.MEDIUM // 0')
        LOW_COUNT=$(echo "$SCAN_FINDINGS" | jq -r '.imageScanFindings.findingSeverityCounts.LOW // 0')
        INFORMATIONAL_COUNT=$(echo "$SCAN_FINDINGS" | jq -r '.imageScanFindings.findingSeverityCounts.INFORMATIONAL // 0')
        UNDEFINED_COUNT=$(echo "$SCAN_FINDINGS" | jq -r '.imageScanFindings.findingSeverityCounts.UNDEFINED // 0')
        
        echo "=========================================="
        echo "AWS Inspector Vulnerability Scan Results"
        echo "=========================================="
        echo "CRITICAL:      $CRITICAL_COUNT"
        echo "HIGH:          $HIGH_COUNT"
        echo "MEDIUM:        $MEDIUM_COUNT"
        echo "LOW:           $LOW_COUNT"
        echo "INFORMATIONAL: $INFORMATIONAL_COUNT"
        echo "UNDEFINED:     $UNDEFINED_COUNT"
        echo "=========================================="
        echo "Environment:   $ENVIRONMENT"
        echo "Blocking Mode: $BLOCK_ON_CRITICAL"
        echo "Override:      $ALLOW_OVERRIDE"
        echo "=========================================="
        
        # Export for notification
        export CRITICAL_COUNT
        export HIGH_COUNT
        export MEDIUM_COUNT
        export LOW_COUNT
        export INFORMATIONAL_COUNT
        export UNDEFINED_COUNT
        
        # Save findings to file for artifact
        echo "$SCAN_FINDINGS" | jq '.' > scan-findings.json
        
        # Create summary report
        cat > scan-summary.txt <<EOF
        ========================================
        AWS Inspector Vulnerability Scan Report
        ========================================
        Scan Engine: AWS Inspector (Enhanced Scanning)
        Environment: $ENVIRONMENT
        Repository: $ECR_REPOSITORY_NAME
        Image Tag: $IMAGE_TAG
        Scan Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        
        Policy Configuration:
        ---------------------
        Block on Critical: $BLOCK_ON_CRITICAL
        Allow Override: $ALLOW_OVERRIDE
        Notification: $ENABLE_NOTIFICATION
        
        Vulnerability Findings:
        -----------------------
        CRITICAL:      $CRITICAL_COUNT
        HIGH:          $HIGH_COUNT
        MEDIUM:        $MEDIUM_COUNT
        LOW:           $LOW_COUNT
        INFORMATIONAL: $INFORMATIONAL_COUNT
        UNDEFINED:     $UNDEFINED_COUNT
        
        Console Link:
        https://console.aws.amazon.com/ecr/repositories/private/${AWS_ACCOUNT_ID}/${ECR_REPOSITORY_NAME}?region=${AWS_DEFAULT_REGION}
        
        AWS Inspector Console:
        https://console.aws.amazon.com/inspector/v2/home?region=${AWS_DEFAULT_REGION}#/findings
        ========================================
        EOF
        
        cat scan-summary.txt
        
  post_build:
    commands:
      # Send notification if enabled
      - |
        if [ "$ENABLE_NOTIFICATION" = "true" ] && [ -n "$SNS_TOPIC_ARN" ]; then
          echo "Sending scan results notification..."
          
          SEVERITY_LABEL="INFO"
          if [ "$CRITICAL_COUNT" -gt 0 ]; then
            SEVERITY_LABEL="CRITICAL"
          elif [ "$HIGH_COUNT" -gt 0 ]; then
            SEVERITY_LABEL="HIGH"
          elif [ "$MEDIUM_COUNT" -gt 0 ]; then
            SEVERITY_LABEL="MEDIUM"
          fi
          
          NOTIFICATION_MESSAGE=$(cat <<EOF
        AWS Inspector Vulnerability Scan Alert - $SEVERITY_LABEL

        Scan Engine: AWS Inspector (Enhanced Scanning)
        Environment: $ENVIRONMENT
        Repository: $ECR_REPOSITORY_NAME
        Image Tag: $IMAGE_TAG
        Scan Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

        Vulnerability Counts:
        - CRITICAL: $CRITICAL_COUNT
        - HIGH: $HIGH_COUNT
        - MEDIUM: $MEDIUM_COUNT
        - LOW: $LOW_COUNT
        - INFORMATIONAL: $INFORMATIONAL_COUNT

        Policy Settings:
        - Block on Critical: $BLOCK_ON_CRITICAL
        - Allow Override: $ALLOW_OVERRIDE

        Action Required:
        $(if [ "$CRITICAL_COUNT" -gt 0 ]; then echo "⚠️  CRITICAL: Application team must fix these vulnerabilities before PROD deployment"; fi)
        $(if [ "$HIGH_COUNT" -gt 0 ]; then echo "⚠️  HIGH: Application team should review and remediate these vulnerabilities"; fi)
        $(if [ "$MEDIUM_COUNT" -gt 0 ]; then echo "ℹ️  MEDIUM: Review recommended for $MEDIUM_COUNT vulnerabilities"; fi)

        View Details:
        ECR Console: https://console.aws.amazon.com/ecr/repositories/private/${AWS_ACCOUNT_ID}/${ECR_REPOSITORY_NAME}?region=${AWS_DEFAULT_REGION}
        Inspector Console: https://console.aws.amazon.com/inspector/v2/home?region=${AWS_DEFAULT_REGION}#/findings
        EOF
          )
          
          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "AWS Inspector Scan Alert [$SEVERITY_LABEL] - $ECR_REPOSITORY_NAME:$IMAGE_TAG" \
            --message "$NOTIFICATION_MESSAGE" \
            --region "$AWS_DEFAULT_REGION" || echo "WARNING: Failed to send SNS notification"
          
          echo "Notification sent to application team via SNS"
        else
          echo "Notification disabled for this environment"
        fi
      
      # Check if deployment should be blocked based on CRITICAL vulnerabilities
      - |
        if [ "$BLOCK_ON_CRITICAL" = "true" ]; then
          if [ "$CRITICAL_COUNT" -gt "$MAX_CRITICAL_FINDINGS" ]; then
            echo "=========================================="
            echo "DEPLOYMENT BLOCKED - CRITICAL VULNERABILITIES DETECTED"
            echo "=========================================="
            echo "Environment: $ENVIRONMENT"
            echo "Found: $CRITICAL_COUNT CRITICAL vulnerabilities"
            echo "Threshold: $MAX_CRITICAL_FINDINGS CRITICAL vulnerabilities allowed"
            echo ""
            echo "Action Required:"
            echo "- Application team must fix CRITICAL vulnerabilities"
            echo "- CVE remediation is required before deployment"
            echo ""
            if [ "$ALLOW_OVERRIDE" = "true" ]; then
              echo "Emergency Override:"
              echo "- Set CODEBUILD_BUILD_OVERRIDE=true in CodeBuild console"
              echo "- Document reason for override in deployment log"
              echo "- Security team will be notified of override"
            fi
            echo ""
            echo "View Vulnerabilities:"
            echo "ECR: https://console.aws.amazon.com/ecr/repositories/private/${AWS_ACCOUNT_ID}/${ECR_REPOSITORY_NAME}?region=${AWS_DEFAULT_REGION}"
            echo "Inspector: https://console.aws.amazon.com/inspector/v2/home?region=${AWS_DEFAULT_REGION}#/findings"
            echo "=========================================="
            
            # Check for emergency override
            if [ "$ALLOW_OVERRIDE" = "true" ] && [ "${CODEBUILD_BUILD_OVERRIDE:-false}" = "true" ]; then
              echo "WARNING: EMERGENCY OVERRIDE ACTIVATED"
              echo "WARNING: Deployment proceeding despite CRITICAL vulnerabilities"
              echo "WARNING: This override has been logged and security team notified"
              # In production, you would log this to CloudWatch/Security Hub
            else
              exit 1
            fi
          else
            echo "No blocking vulnerabilities found (CRITICAL: $CRITICAL_COUNT <= $MAX_CRITICAL_FINDINGS)"
          fi
        else
          echo "=========================================="
          echo "WARNING MODE - $ENVIRONMENT Environment"
          echo "=========================================="
          if [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "Found $CRITICAL_COUNT CRITICAL vulnerabilities"
            echo "WARNING: Deployment NOT blocked in $ENVIRONMENT (warn only)"
            echo "WARNING: Application team should fix these vulnerabilities before PROD"
            echo ""
            echo "View Vulnerabilities:"
            echo "ECR: https://console.aws.amazon.com/ecr/repositories/private/${AWS_ACCOUNT_ID}/${ECR_REPOSITORY_NAME}?region=${AWS_DEFAULT_REGION}"
            echo "Inspector: https://console.aws.amazon.com/inspector/v2/home?region=${AWS_DEFAULT_REGION}#/findings"
          else
            echo "No CRITICAL vulnerabilities found"
          fi
          echo "=========================================="
        fi
      
      - echo "=========================================="
      - echo "Scan validation passed"
      - echo "=========================================="

artifacts:
  files:
    - scan-findings.json
    - scan-summary.txt
  name: scan-results
