version: 0.2

# CodeBuild BuildSpec for Docker Build and Push to ECR
# Stage 1: Build - Build Docker image and push to Amazon ECR
# Trigger: CodePipeline Source stage (GitHub via CodeStar Connection)
# Next: AWS Inspector automatically scans image on push to ECR

env:
  variables:
    AWS_DEFAULT_REGION: "ap-southeast-1"
    ENVIRONMENT: "sit"
    ECR_REPOSITORY_NAME: "hlf-lab-ecr-sit-test-app"
    # Build configuration
    DOCKER_BUILDKIT: "1"
    
phases:
  pre_build:
    commands:
      - echo "=========================================="
      - echo "Stage 1 Docker Build and Push to ECR"
      - echo "=========================================="
      - echo "Environment=$ENVIRONMENT"
      - echo "Region=$AWS_DEFAULT_REGION"
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export ECR_REPOSITORY_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}"
      - export COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - export SHORT_HASH=$(echo ${COMMIT_HASH} | cut -c1-7)
      - export IMAGE_TAG=${SHORT_HASH}
      - echo "Commit Hash (full)=$COMMIT_HASH"
      - echo "Image Tag (short-hash)=$IMAGE_TAG"
      - echo "ECR Repository URI=$ECR_REPOSITORY_URI"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REPOSITORY_URI}
      - echo "Logged in to ECR successfully"
      - echo "=========================================="

  build:
    commands:
      - echo "Building Docker image..."
      - docker build --tag ${ECR_REPOSITORY_URI}:${IMAGE_TAG} --tag ${ECR_REPOSITORY_URI}:latest --build-arg BUILDKIT_INLINE_CACHE=1 .
      - echo "Docker image built successfully"
      - docker images | grep ${ECR_REPOSITORY_NAME}

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push ${ECR_REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${ECR_REPOSITORY_URI}:latest
      - echo "Image pushed to ECR successfully"
      - echo "=========================================="
      - echo "Build Stage Complete"
      - echo "=========================================="
      - echo "Image URI ${ECR_REPOSITORY_URI}:${IMAGE_TAG}"
      - echo "Latest URI ${ECR_REPOSITORY_URI}:latest"
      - echo "ECR Console https://console.aws.amazon.com/ecr/repositories/private/${AWS_ACCOUNT_ID}/${ECR_REPOSITORY_NAME}?region=${AWS_DEFAULT_REGION}"
      - echo ""
      - echo "Next Stage AWS Inspector Vulnerability Scan"
      - echo "Scan Type OS packages + Programming language packages"
      - echo "Inspector automatically scans on image push to ECR"
      - echo "=========================================="
      - echo "{\"imageTag\":\"${IMAGE_TAG}\",\"imageUri\":\"${ECR_REPOSITORY_URI}:${IMAGE_TAG}\",\"repository\":\"${ECR_REPOSITORY_NAME}\"}" > build-output.json
      - cat build-output.json

artifacts:
  files:
    - build-output.json
    - buildspec_scan.yml
    - buildspec_module.yml
    - scripts/**/*
    - script/**/*
    - manifests/**/*
    - charts/**/*
  name: build-artifacts
